apiVersion: v1
kind: Service
metadata:
 name: db
spec:
 selector:
    app: db
 ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: db
spec:
 replicas: 1
 selector:
    matchLabels:
      app: db
 template:
    metadata:
      labels:
        app: db
    spec:
      initContainers:
      - name: init-db
        image: mysql:8.0
        command: ['sh', '-c', 'until nslookup db; do echo waiting for db; sleep 2; done;']
        volumeMounts:
        - name: init-db-scripts
          mountPath: /docker-entrypoint-initdb.d
      containers:
      - name: db
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: root
        - name: MYSQL_ROOT_PASSWORD
          value: root
        volumeMounts:
        - name: init-db-scripts
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-db-scripts
        configMap:
          name: init-db-scripts

---
# The rest of your cart.yaml remains unchanged

apiVersion: v1
kind: Service
metadata:
 name: web
spec:
 ports:
    - port: 8002
      targetPort: 8002
      nodePort: 30002
 selector:
    app: web
 type: NodePort 

---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: web
spec:
 replicas: 1
 selector:
    matchLabels:
      app: web
 template:
    metadata:
      labels:
        app: web
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup db; do echo waiting for db; sleep 2; done;']
      containers:
        - name: web
          image: pavvanpradeep/cart-web
          ports:
            - containerPort: 8002
          env:
            - name: DATABASE_HOST
              value: db
          imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
 name: queue
spec:
 ports:
    - port: 8003
 selector:
    app: queue

---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: queue
spec:
 replicas: 1
 selector:
    matchLabels:
      app: queue
 template:
    metadata:
      labels:
        app: queue
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup db; do echo waiting for db; sleep 2; done;']
      containers:
        - name: queue
          image: pavvanpradeep/cart-queue
          command: ["python", "consumer.py"]
          imagePullPolicy: IfNotPresent
